const errorsType={
    NOT_FOUND: "NOT_FOUND",
    NOT_AUTHORIZED: "NOT_AUTHORIZED",
    NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
    NOT_VALID: "NOT_VALID",
    NOT_UNIQUE: "NOT_UNIQUE",
    NOT_ALLOWED: "NOT_ALLOWED",
    NOT_ACCEPTABLE: "NOT_ACCEPTABLE",
    NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
    NOT_AVAILABLE: "NOT_AVAILABLE",
    NOT_SUPPORTED: "NOT_SUPPORTED",
    NOT_DEFINED: "NOT_DEFINED",
    NOT_ALLOWED: "NOT_ALLOWED",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
}
module.exports = errorsType;    