const router = require('express').Router();
const userRoutes = require('./UserRoutes');
const roleRoutes = require('./RoleRoutes');
const permissionRoutes = require('./PermissionRoutes');
const fileUploadRoutes = require('./FileUploadRoutes');
router.use('/user',userRoutes);
router.use('/role',roleRoutes);
router.use('/permission',permissionRoutes);
router.use('/file',fileUploadRoutes);
module.exports =  router;